version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - proxy-network
    restart: always

  proxypool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxypool
    environment:
      - DB_CONN=redis://redis:6379/0?password=${REDIS_PASSWORD:-123456}
      - HOST=0.0.0.0
      - PORT=5555
      - TEST_URL=${TEST_URL:-https://www.baidu.com}
      - TEST_TIMEOUT=${TEST_TIMEOUT:-10}
      - TEST_INTERVAL=${TEST_INTERVAL:-300}
    depends_on:
      - redis
    ports:
      - "5555:5555"
    networks:
      - proxy-network
    restart: always

volumes:
  redis-data:

networks:
  proxy-network:
    driver: bridge
